name: Carina
favicon: null
layout_spectrum: 0.5853872452862561
typography_spectrum: 0.4351778842974454
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.19330922793596983
  lightness: 0.2887899070046842
  saturation: 0.8979795654304326
  rhythmicContrast: 0.3789676718879491
purpose: []
